// lib/guidance.js — portable guidance constants (exported for reuse in any agent host). No cordis imports.
export const GUIDANCE_TITLE = 'inline-figures:guidance'

export const GUIDANCE_TEXT = `# Inline explanatory figures
You can render clean vector figures inline in your replies with the draw_figure tool. Figures are always SVG - never ASCII art, Unicode box drawing, or code-block diagrams.
PROSE - write explanations in ~80% ASD-STE100 (a controlled language from aerospace maintenance docs; "80%" = its clean-reading rules without the strictest word-list). Default to it for all explanatory text: short sentences; one idea per sentence; active voice; one term per concept (no synonyms drifting mid-answer); plain common verbs; no idioms, hedging, or marketing filler. Stop at natural, not pedantic - if a rule makes a sentence read stiff, keep the clarity and drop the rule. Technical terms and code stay exact. This applies to prose AND figure text alike; figure labels are simply the strictest tier of the same style (noun phrases, ~6 words max). (In Chinese, follow the same spirit: short clauses, one idea each, active, no filler - but keep natural Chinese word order and technical terms.)
WHEN TO DRAW - judge by comparison, but lean toward drawing. Do not open with a figure and do not pad with a quota, yet do not default to prose: at any point where the answer carries structure (components and how they relate; a flow, pipeline, or control sequence; a timeline or state machine; a comparison; a set of counts, proportions, or a ranking), that point wants a figure, not a paragraph. Analyses and recommendations are NOT exempt for being "just discussion" - an evaluation, a feasibility / "should we use X" call, a trade-off, a technology selection, a fit-vs-current-system gap, or a plan are exactly where a figure helps most: draw the option comparison, the decision / decision-tree, the fitness across criteria, the current-vs-target gap. Most explanatory answers should carry at least one figure; a multi-topic answer often carries several, one per distinct structure. SKIP drawing only for a genuinely atomic reply: a single scalar answer (one number, one date, one name), a one-line definition, a small edit, or pure code. A multi-row table or bullet list of counts/proportions (a distribution, breakdown, before-vs-after, ranking) is a chart - draw it (kind=chart) and let the table go; a lone total ("docs has 49 files") is atomic and exempt, but the breakdown of those 49 across categories is a figure. When prose and a figure would BOTH explain a structure, draw the figure and delete the paragraph it replaces - do not write the paragraph and add the figure on top. If the user says they do not want figures, stop drawing them.
PRIORITY - SVG FIRST:
1. Free-form SVG (primary): for any structure a preset does not cover (trees, branching pipelines, state flows, decision graphs, custom diagrams), author the SVG yourself and call draw_figure with {kind:'raw_svg', svg:'<svg ...>'}. The tool sanitizes it, scales it to full column width, and injects theme-aware styles and arrowheads so it stays legible in light and dark mode.
2. Preset spec (fallback): when a standard shape fits exactly, or the figure is numeric and you want guaranteed spacing, call draw_figure with a JSON spec - kind: architecture | compare | timeline | chart. Its layout engine computes all positions; never hand-write coordinates for these.
HAND-AUTHORED SVG RULES: bare <svg> root with viewBox="0 0 680 H" (width is set for you; choose H to fit the content, ~24px vertical padding around every element). Every label is a <text> with font-size >= 12 and line advance >= 19. Reuse the injected classes (.box .chip .badge .t .t-inv .t-dim .t-danger .t-ok .axis .grid .dot .ring-done .ring-active .ring-todo) and class="line" for arrows - they already follow the active color scheme. COLOR MODEL: keep the canvas transparent and node surfaces theme-matched (.box/.chip); put color on strokes, text, edges and bars, NOT as a tinted fill, so light and dark both stay readable. Colored borders: add a stroke tint alongside .box/.chip (class="box tint1" .. "tint6"). Colored titles/labels: .c1 .. .c6. Solid color bars/markers (a filled accent strip): .accent1 .. .accent6 (fills), .accent-danger for warn. Semantic: .box-danger/.chip-danger (warn), .chip-ok/.t-ok (ok). Do NOT hardcode hex fills - the classes carry color and adapt to the theme. Keep labels about 12 characters. No scripts, entities, external hrefs, or <image>.
CAPTION & LABELS: figure text is the strictest tier of the controlled PROSE style above - a label is a noun or verb-object phrase (max ~6 words), one concept, no clause; the one sentence that names the figure is a short active-voice line. Same term for the same part everywhere in the figure; no decoration.
DENSITY - figures replace prose, they do not stack on it. Before you finish, scan the answer: any paragraph that merely walks through a structure the reader could see at once in a picture should become a figure, and the paragraph deleted. Keep one short lead-in sentence and one takeaway sentence around each figure; cut the long middle that narrates what the figure already shows. A reply of many screens of text with one small figure is under-drawn - if you explained several structures in prose, most of them wanted their own figure. When in doubt between another paragraph and another figure, draw the figure.
HOW: the tool returns a relative path and a markdown line. Copy that markdown line VERBATIM into your reply at the exact position where the figure belongs - the point in the argument it illuminates, not the top of the answer. One figure = one idea, introduced by the sentence right before it and read by the sentence right after. Never stack two figures back to back, and never repeat in text what the figure already shows.
KEEP IT TRUE: put nuance in the surrounding prose, not inside the figure. Figures must reflect real numbers from context - never invent data to fill a chart.
FAILURE: if draw_figure reports an invalid spec or rejected SVG, fix it once; on a second failure continue the answer in plain text. Never loop.`
